### ISSUE TITLE
运行时出现这个错误

### ISSUE THREAD

**Issue by Serialism** [FokersBoolean/AliceBot#8]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatGPTController': Unsatisfied dependency expressed through field 'chatGPTService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatGPTServiceImpl': Unsatisfied dependency expressed through field 'chatbot'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatBot' defined in cn.penidea.alice.AliceApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.penidea.alice.chatgpt.Chatbot]: Factory method 'chatBot' threw exception; nested exception is java.lang.Exception: Error refreshing session
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.24.jar!/:5.3.24]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.24.jar!/:5.3.24]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.7-SNAPSHOT.jar!/:2.7.7-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) [spring-boot-2.7.7-SNAPSHOT.jar!/:2.7.7-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) [spring-boot-2.7.7-SNAPSHOT.jar!/:2.7.7-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.7.7-SNAPSHOT.jar!/:2.7.7-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.7-SNAPSHOT.jar!/:2.7.7-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.7-SNAPSHOT.jar!/:2.7.7-SNAPSHOT]
        at cn.penidea.alice.AliceApplication.main(AliceApplication.java:51) [classes!/:0.0.2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_351]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_351]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_351]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_351]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [Alice-0.0.2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [Alice-0.0.2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [Alice-0.0.2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [Alice-0.0.2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatGPTServiceImpl': Unsatisfied dependency expressed through field 'chatbot'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatBot' defined in cn.penidea.alice.AliceApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.penidea.alice.chatgpt.Chatbot]: Factory method 'chatBot' threw exception; nested exception is java.lang.Exception: Error refreshing session
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.3.24.jar!/:5.3.24]
        ... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatBot' defined in cn.penidea.alice.AliceApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.penidea.alice.chatgpt.Chatbot]: Factory method 'chatBot' threw exception; nested exception is java.lang.Exception: Error refreshing session
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.3.24.jar!/:5.3.24]
        ... 42 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.penidea.alice.chatgpt.Chatbot]: Factory method 'chatBot' threw exception; nested exception is java.lang.Exception: Error refreshing session
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.24.jar!/:5.3.24]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.24.jar!/:5.3.24]
        ... 55 common frames omitted
Caused by: java.lang.Exception: Error refreshing session
        at cn.penidea.alice.chatgpt.Chatbot.refreshSession(Chatbot.java:272) ~[classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.chatgpt.Chatbot.<init>(Chatbot.java:40) ~[classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.AliceApplication.chatBot(AliceApplication.java:107) [classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.AliceApplication$$EnhancerBySpringCGLIB$$434d2389.CGLIB$chatBot$1(<generated>) ~[classes!/:0.0.2-SNAPSHOT]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.24.jar!/:5.3.24]
        ... 55 common frames omitted
Caused by: java.lang.Exception: Error refreshing session
        at cn.penidea.alice.chatgpt.Chatbot.refreshSession(Chatbot.java:272) ~[classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.chatgpt.Chatbot.<init>(Chatbot.java:40) ~[classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.AliceApplication.chatBot(AliceApplication.java:107) [classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.AliceApplication$$EnhancerBySpringCGLIB$$434d2389.CGLIB$chatBot$1(<generated>) ~[classes!/:0.0.2-SNAPSHOT]
        at cn.penidea.alice.AliceApplication$$EnhancerBySpringCGLIB$$434d2389$$FastClassBySpringCGLIB$$267be08b.invoke(<generated>) ~[classes!/:0.0.2-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.24.jar!/:5.3.24]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.24.jar!/:5.3.24]
        at cn.penidea.alice.AliceApplication$$EnhancerBySpringCGLIB$$434d2389.chatBot(<generated>) ~[classes!/:0.0.2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_351]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_351]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_351]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_351]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.24.jar!/:5.3.24]
        ... 56 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: illegal input? offset 1, char <
        at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1432) ~[fastjson2-2.0.20.jar!/:na]
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:193) ~[fastjson2-2.0.20.jar!/:na]
        at cn.penidea.alice.chatgpt.Chatbot.refreshSession(Chatbot.java:262) ~[classes!/:0.0.2-SNAPSHOT]
        ... 68 common frames omitted

**Comment by Arturia169** [comment]
我也是这个错误 楼主解决了吗

**Comment by Serialism** [comment]
解决不了，我这个前几天还运行得好好的，今天上午五点半左右突然就出这个错误了，可能跟openai加了cloudflare有关
